# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets
from bert_model import BertModel


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1020, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(1020, 720))
        MainWindow.setStyleSheet("background-color: rgb(2, 59, 57);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 991, 551))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_logo = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_logo.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_logo.setFont(font)
        self.label_logo.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_logo.setStyleSheet("color: rgb(221, 221, 221);")
        self.label_logo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_logo.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_logo.setText("")
        self.label_logo.setTextFormat(QtCore.Qt.AutoText)
        self.label_logo.setPixmap(QtGui.QPixmap("logo.png"))
        self.label_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_logo.setWordWrap(False)
        self.label_logo.setObjectName("label_logo")
        self.horizontalLayout_2.addWidget(self.label_logo)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_title = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_title.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_title.setMargin(20)
        self.label_title.setFont(font)
        self.label_title.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_title.setStyleSheet("color: rgb(221, 221, 221);")
        self.label_title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_title.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_title.setTextFormat(QtCore.Qt.AutoText)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setWordWrap(False)
        self.label_title.setObjectName("label_title")
        self.horizontalLayout_3.addWidget(self.label_title)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_review = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_review.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_review.setMargin(10)
        self.label_review.setFont(font)
        self.label_review.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_review.setStyleSheet("color: rgb(221, 221, 221);")
        self.label_review.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_review.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_review.setTextFormat(QtCore.Qt.AutoText)
        self.label_review.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_review.setWordWrap(False)
        self.label_review.setObjectName("label_review")
        self.horizontalLayout.addWidget(self.label_review)
        self.lineEdit_review = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_review.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_review.setFont(font)
        self.lineEdit_review.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_review.setAutoFillBackground(False)
        self.lineEdit_review.setTextMargins(10, 0, 0, 0)
        self.lineEdit_review.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"color: rgb(68, 68, 68);\n"
"border-radius: 10px;")
        self.lineEdit_review.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_review.setInputMask("")
        self.lineEdit_review.setText("")
        self.lineEdit_review.setFrame(True)
        self.lineEdit_review.setAlignment(QtCore.Qt.AlignLeft)
        self.lineEdit_review.setClearButtonEnabled(True)
        self.lineEdit_review.setObjectName("lineEdit_review")
        self.horizontalLayout.addWidget(self.lineEdit_review)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_rating = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_rating.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_rating.setFont(font)
        self.label_rating.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_rating.setStyleSheet("color: rgb(255, 149, 41);")
        self.label_rating.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_rating.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_rating.setText("")
        self.label_rating.setTextFormat(QtCore.Qt.AutoText)
        self.label_rating.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rating.setWordWrap(False)
        self.label_rating.setObjectName("label_review_2")
        self.horizontalLayout_5.addWidget(self.label_rating)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.pushButton_predict = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_predict.setGeometry(QtCore.QRect(380, 590, 250, 61))
        self.pushButton_predict.setMaximumSize(QtCore.QSize(250, 1000))
        self.pushButton_predict.setStyleSheet("QPushButton {\n"
"    font: 75 16pt \"MS Shell Dlg 2\";\n"
"    color: rgb(221, 221, 221);\n"
"    background-color: qlineargradient(x1: 0, y1: 0 x2: 1, y2: 0, stop: 0 #008487, stop: 1 #005B7C);\n"
"    border-radius: 30px;\n"
"    border: 1px solid #8f8f91;\n"
"}\n"
"QPushButton:pressed {\n"
"    font: 75 16pt \"MS Shell Dlg 2\";\n"
"    color: rgb(221, 221, 221);\n"
"    background-color: qlineargradient(x1: 0, y1: 0 x2: 1, y2: 0, stop: 0 #005B7C, stop: 1 #008487);\n"
"    border-radius: 30px;\n"
"    border: 1px solid #8f8f91;\n"
"} ")
        self.pushButton_predict.setCheckable(True)
        self.pushButton_predict.setChecked(False)
        self.pushButton_predict.setObjectName("pushButton_led")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1020, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton_predict.clicked.connect(self.onPredictClick)

        


    def retranslateUi(self, MainWindow):
        self.bert_model = BertModel()
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sentiment Analysis on Movie Reviews"))
        self.label_title.setText(_translate("MainWindow", "Sentiment Analysis on Movie Reviews"))
        self.label_review.setText(_translate("MainWindow", "Review"))
        self.lineEdit_review.setPlaceholderText(_translate("MainWindow", "Example: I liked this movie."))
        self.pushButton_predict.setText(_translate("MainWindow", "PREDICT"))
        self.label_rating.setText(_translate("MainWindow", self.bert_model.stars[5]))

    
    def onPredictClick(self):
        review = self.lineEdit_review.text().strip()
        if review == "":
            self.label_rating.setText(self.bert_model.stars[5])
        else:
            prediction = self.bert_model.predict_review(review)
            self.label_rating.setText(prediction)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    app.setQuitOnLastWindowClosed(True)
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())